# Generated by Django 5.1.7 on 2025-03-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_location', models.CharField(max_length=255)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('total_miles_driven_today', models.IntegerField()),
                ('total_mileage_today', models.IntegerField()),
                ('vehicle_numbers', models.CharField(max_length=255)),
                ('carrier_name', models.CharField(max_length=255)),
                ('main_office_address', models.TextField()),
                ('home_terminal_address', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('shipping_documents', models.CharField(blank=True, max_length=255, null=True)),
                ('dvi_or_manifest_no', models.CharField(blank=True, max_length=255, null=True)),
                ('current_cycle_used', models.IntegerField()),
            ],
        ),
    ]
